name: C++ CI

on: push

env:
  PROJECT_NAME: "v-editor"
  APP_NAME: "v-editor"

jobs:
    build-documentation:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3

          - name: Doxygen action
            uses: mattnotmitt/doxygen-action@v1.1.0
            with:
                doxyfile-path: ./Doxyfile
                workong-directory: .
          
          - name: Github Pages deployment
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{secrets.GITHUB_TOKEN}}
                publish_dir: ./docs/html/
                enable_jekyll: false
                allow_empty_commit: false
                force_orphan: true
                publish_branch: gh-pages

    build-deb:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with: 
                submodules: true
              
            - name: Install deps and configure env
              run: |
                sudo apt update && sudo apt install git ninja-build g++ cmake -y
                git clone https://github.com/microsoft/vcpkg.git && cd ./vcpkg
                sudo ./bootstrap-vcpkg.sh -disableMetrics
                sudo ./vcpkg integrate install
              
            - name: Build using CMake
              run: | 
                export VCPKG_ROOT=$PWD/vcpkg
                ./vcpkg/vcpkg install
                cmake
                cmake -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
                  -DPATCH_VERSION=${{ github.run_number }} \
                  --preset=vcpkg-release -S . -B build
                cmake --build build --target ${{env.PROJECT_NAME}} 
                cmake --build build --target package
            
            - name: Create release
              id: create-release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: 0.0.${{ github.run_number}}
                release_name: ${{env.APP_NAME}}-0.0.${{ github.run_number }}
                draft: false
              
            - name: Upload DEB release
              id: upload-deb-release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create-release.outputs.upload_url }}
                asset_path: ./build/${{env.APP_NAME}}-0.0.${{ github.run_number }}-Linux.deb
                asset_name: ${{env.APP_NAME}}-0.0.${{ github.run_number }}-Linux.deb
                asset_content_type: application/vnd.debian.binary-package